---
env:
- PUPPET_VERSION=3.3.2
- PUPPET_VERSION=3.4.2
notifications:
email: false
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
language: ruby
before_script: 'gem install --no-ri --no-rdoc bundler'
script: 'puppet-lint  --log-format %{filename}.%{line}.%{column}.%{message}.%{check} manifests/'
gemfile: Gemfile
